version: '3.5'

services:
  api-gateway:
    # build:
    #   context: ./spring-framework/api_gateway-service
    image: itmagician/ssafy-b309:api-gateway-service
    container_name: api-gateway
    ports:
      # - "80:80"
      - "443:443"
    networks:
      - playground-broadcast-network

  oauth2-service:
    # build: 
    #   context: ./spring-framework/oauth_service
    image: itmagician/ssafy-b309:oauth2-service
    container_name: playground-oauth2-service
    environment:
      - server.port=9001
    ports:
      - "9001:9001"
    networks:
      - playground-broadcast-network

  oauth2-service2:
    # build: 
    #   context: ./spring-framework/oauth_service
    image: itmagician/ssafy-b309:oauth2-service
    container_name: playground-oauth2-service2
    environment:
      - server.port=9011
    ports:
      - "9011:9011"
    networks:
      - playground-broadcast-network

  user-service:
    # build: 
    #   context: ./spring-framework/user-service
    image: itmagician/ssafy-b309:user-service
    container_name: user-service
    environment:
      - server.port=9002
    ports:
      - "9002:9002"
    networks:
      - playground-broadcast-network

  matching-service:
    # build: 
    #   context: ./spring-framework/matching
    image: itmagician/ssafy-b309:matching-service
    container_name: matching-service
    environment:
      - server.port=9003
    ports:
      - "9003:9003"
    networks:
      - playground-broadcast-network

  notify-service:
    # build: 
    #   context: ./spring-framework/fcm-service
    image: itmagician/ssafy-b309:notify-service
    container_name: notify-service
    environment:
      - server.port=9004
    ports:
      - "9004:9004"
    networks:
      - playground-broadcast-network
    # depends_on:
    # - matching-service
    # - user-service


  chat-service:
    # build: 
    #   context: ./spring-framework/fcm-service
    image: itmagician/ssafy-b309:chat-service
    container_name: chat-service
    environment:
      - server.port=9005
    ports:
      - "9005:9005"
    networks:
      - playground-broadcast-network

  team_matching-service:
    # build: 
    #   context: ./spring-framework/fcm-service
    image: itmagician/ssafy-b309:team_matching-service
    container_name: team_matching-service
    environment:
      - server.port=9006
    ports:
      - "9006:9006"
    networks:
      - playground-broadcast-network

  react-framework:
    # build: 
    #   context: ./spring-framework/fcm-service
    image: itmagician/ssafy-b309:react-framework
    container_name: react-framework
    ports:
      - "3000:80"
    networks:
      - playground-broadcast-network

networks:
  playground-broadcast-network:
    name: playground-broadcast-network
    driver: bridge
