
eureka:
  instance:
    hostname: www.b309-playground.com
  #    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
  #    secure-port: ${env.server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://www.b309-playground.com:8761/eureka

spring:
  application:
    name: USER-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssafy-project.mysql.database.azure.com:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: ssafy
    password: b309oob309oo*&




  jpa:
    show-sq: true
    hibernate:
      ddl-auto: update # validate #
    properties:
      hibernate:
        format_sql: true

# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above

