spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    prefix: /chat/
    suffix: .ftl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
  redis:
    host: www.b309-playground.com # i8b309.p.ssafy.io # localhost
    port: 6379
    password: b309309
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssafy-project.mysql.database.azure.com:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: ssafy
    password: b309oob309oo*&


#    url: jdbc:mysql://i8b309.p.ssafy.io:3333/playground?serverTimezone=UTC&characterEncoding=UTF-8
#    username: ssafy
#    password: b309oo

# jdbc:mysql://localhost:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8

server:
  ssl:
    enabled: true
    key-store: classpath:chat-service.p12
    key-store-password: b309309
  port: 8080



